### ISSUE TITLE
XCP-ng: Cluster Prepare: vm-disk-add failure

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1056]
I'm seeing these failures when provisioning a cluster on XCP-ng:

![image](https://user-images.githubusercontent.com/4908431/98147420-588a3880-1e81-11eb-8e4a-5a93f8bb6295.png)

Hmmm: The error is [insufficient space](https://www.quadricsoftware.com/knowledge-base/xenserver-error-sr-backend-failure-44-insufficient-space/)

This server has about 1.5 TiB of storage so there should be plenty of disk space:

![image](https://user-images.githubusercontent.com/4908431/98148821-e36b3300-1e81-11eb-9aa7-137e6a8fa703.png)

...and my cluster definition isn't explicitly specifying any disk sizes so I presume the **defaults must be too large?**

```
name: small-xcp-home
datacenter: sultan
environment: development
linuxDistribution: ubuntu
linuxVersion: 20.04.latest
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: xenserver
  vm:
    hostUsername: $<<XENSERVER_USERNAME>>
    hostPassword: $<<XENSERVER_PASSWORD>>
    namePrefix: jeff
    hosts:
    - name: XCP-HOME
      address: 10.0.0.5
  xenServer:
     snapshot: true
network:
  premiseSubnet: 10.0.0.0/16
nodeOptions:
   upgrade: none
nodes:
  master-0:
    role: master
    address: 10.0.1.30
    openEbs: true
    vm:
      host: XCP-HOME
  worker-0:
    role: worker
    address: 10.0.1.40
    openEbs: true
    vm:
      host: XCP-HOME
  worker-1:
    role: worker
    address: 10.0.1.41
    openEbs: true
    vm:
      host: XCP-HOME
  worker-2:
    role: worker
    address: 10.0.1.42
    openEbs: true
    vm:
      host: XCP-HOME
```
