### ISSUE TITLE
TemporalFixture failing because Cassandra is terminated by the OOM killer

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1099]
Temporal unit tests are failing on my workstation because the fixture cannot connect to the temporal service.  The problem is that Cassandra is being killed by the WSL2 OOM killer.  This also happens when I switch to Docker/Hyper-V.  I believe the problem is due to the Temporal fixture compose file limiting Cassandra to 1GiB RAM but Cassandra is probably using `free` to see how much memory is available and is trying to allocate too much because `free` doesn't know about docker resource limits.

It looks like we're using the standard **Cassandra:3.11** container image.  I think we may need to create a custom image that munges the startup script to use `cat /sys/fs/cgroup/memory/memory.limit_in_bytes` or something to retrieve the correct limit.

I'll have a look.  It seems like we already had to so something like this for the `cadence-dev` image.

**Comment by jefflill** [comment]
OK: I fixed this by passing some environment variables to the Cassandra container in the compose file:
```
version: '3.5'

# IMPORTANT NOTE: 
#
# We're setting the Cassandra container memory limit to 1024M below and
# then passing the [MAX_HEAP_SIZE=924M] environment variable which tells
# Cassandra how much memory it can allocate.  This number is 100M lower
# than the container limit to account for additional RAM overhead for
# Bash, etc.
#
# This means that you'll need to adjust [MAX_HEAP_SIZE] whenever you
# change the memory limit.

services:
  cassandra:
    image: cassandra:3.11
    environment:
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1000M
    deploy:
      resources:
        limits:
          memory: 1024M
  temporal:
    image: temporalio/auto-setup:1.1.0
    ports:
      - '7233:7233'
    environment:
      - 'CASSANDRA_SEEDS=cassandra'
      - 'DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml'
    depends_on:
      - cassandra
  temporal-web:
    image: temporalio/web:1.1.0
    environment:
      - 'TEMPORAL_GRPC_ENDPOINT=temporal:7233'
      - 'TEMPORAL_PERMIT_WRITE_API=true'
    ports:
      - '8088:8088'
    depends_on:
      - temporal
```
This is fairly clean.  I did set `MAX_HEAP_SIZE` to 100MB less than the container's memory limit to account for additional container memory used by bash, etc.  I'm not sure this is a reasonable best practice but without doing this, it seems possible for Cassandra to still try to allocate too much RAM and get killed.
