### ISSUE TITLE
Node image prepositioning

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1110]
Cluster setup is currently slow and unreliable due to the need to perform significant network operations to download and install packages, programs as well as pull container images.  This is slow because we need to do this for every node being deployed and DockerHub and other image repositories often throttle downloads (sometimes quite substantially).

So the idea is to preposition this stuff on the VM images so that we won't need to download a bunch of files during setup.  This will make VM images neonKUBE version specific going forward.

**Prepositioned Assets:**

There are three kinds of assets we should preposition:

* Ubuntu packages: these can just be installed by the image prepare tool.
* Docker is preinstalled on the image
* Docker images: the prepare tool pushes/loads these to the local Docker image cache
* Binaries: the prepare tool writes these to `/lib/neonkube/setup`
* Scripts: the prepare tool also writes these to `/lib/neonkube/setup` (these are the files we were going to embed as resources but will no longer have to)

The image prepare tool would accept a new command line argument that specifies the path of a text file that describes the files to be installed.  I'm thinking of a simple YAML file format like:
```
packages:
  - package1-name
  - package2-name
scripts:
  - script1-relative-path
  - script2-relative-path
downloads:
  - url: download-url-1
    file: download-1.tar
  - url: download-url-2
    file: download-2.tar
images:
  - image: nkubeio/image-1:2.0
    file: nkubeio.image-1.image
  - image: nkubeio/image-2:2.0
    file: nkubeio.image-2.image
```
The image prepare tool will simply install the named packages when it's generating the image and upload any script files.  Note that the script file paths will be relative to the current cloned repo root.

Downloads will be processed by fetching the URL contents to the specified file name in the setup folder.  We should also figure out a local workstation caching strategy so we need to download this stuff over and over while we're debugging and testing.  neonDESKTOP setup already uses the `$/BuildCache` folder to cache the **kubectl** client tool so we can probably piggyback on that.

Images will be specified by their container image URL and the name of the file used to cache the container image.

**Archival**

I've been thinking that it would be nice to archive all of this in S3 or someplace, perhaps as ZIP file for each neonKUBE/DESKTOP release but I'm not sure it's worth the trouble.  Ideally, we'd also download and archive the Ubuntu packages, but that's easier said than done, because we'd need to download any dependencies as well.  Everything else will be easily obtainable from the VM images themselves, so we could just start one, login and fetch anything we need from that.
