### ISSUE TITLE
XenServer cluster setup fails with NullReferenceException

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1293]
@granth7: reported seeing a `NullReferenceException` while setting up a XenServer hosted cluster.

I was able to repro this on Sunday but haven't had a chance to have a detailed look until after fixing some bugs blocking **neon-image** from rebuilding the XenServer base and node images (which are fixed now).

Here's the repro cluster definition:
```
name: wrt-00-spark
datacenter: wrt-00
environment: test
timeSources:
- pool.ntp.org
kubernetes:
  apiLoadBalancer: wrt-00.spark.loopie.io:6443
hosting:
  environment: xenserver
  vm:
    hostUsername: $<<XENSERVER_USERNAME>>
    hostPassword: $<<XENSERVER_PASSWORD>>
    namePrefix: loopie-spark
    hosts:
    - name: WRT-00-XEN-00
      address: 10.100.128.85
    - name: WRT-00-XEN-01
      address: 10.100.128.91
    - name: WRT-00-XEN-02
      address: 10.100.128.97
    - name: WRT-00-XEN-03
      address: 10.100.128.103
    - name: WRT-00-XEN-04
      address: 10.100.128.109
    - name: WRT-00-XEN-07
      address: 10.100.128.127
    - name: WRT-00-XEN-08
      address: 10.100.128.133
  xenServer:
    snapshot: true
network:
  premiseSubnet: 10.100.0.0/16
  gateway: "10.100.0.1"
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
openEbs:
  engine: cstor
nodes:
  master-0:
    role: master
    address: 10.100.116.1
    vm:
      host: WRT-00-XEN-07
      cores: 4
      memory: 8 GiB
      osDisk: 64 GiB
  master-1:
    role: master
    address: 10.100.116.2
    vm:
      host: WRT-00-XEN-07
      cores: 4
      memory: 8 GiB
      osDisk: 64 GiB
  master-2:
    role: master
    address: 10.100.116.3
    vm:
      host: WRT-00-XEN-07
      cores: 4
      memory: 8 GiB
      osDisk: 64 GiB
  worker-0:
    role: worker
    address: 10.100.116.100
    openEbsStorage: true
    vm:
      host: WRT-00-XEN-08
      cores: 4
      memory: 16 GiB
      osDisk: 64 GiB
      openEbsDisk: 64 GiB
  worker-1:
    role: worker
    address: 10.100.116.101
    openEbsStorage: true
    vm:
      host: WRT-00-XEN-08
      cores: 4
      memory: 16 GiB
      osDisk: 64 GiB
      openEbsDisk: 64 GiB
  worker-2:
    role: worker
    address: 10.100.116.102
    vm:
      host: WRT-00-XEN-08
      cores: 4
      memory: 16 GiB
      osDisk: 64 GiB
      openEbsDisk: 64 GiB
```

...and here are the setup commands:
```
neon logout
neon login rm --force root@wrt-00-spark
neon cluster prepare %NC_ROOT%/devops/loopie/wrt-00-spark.cluster.yaml --unredacted
neon cluster setup --unredacted root@wrt-00-spark
```
