### ISSUE TITLE
neon-node-agent: ClusterRegistry custom resource

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1380]
Implement the **ClusterRegistry** custom resource to manage CRI-O upstream container repositories:

- [x] Default registries
- [x] Registry redirection
- [x] Registry credentials
- [x] Registry blocking
- [x] Insecure registries
- [x] Event re-queue interval and other configuration settings

This will be implemented by **neon-node-agent** who will watch these resources and update the local CRI-O config as required.

Note that it's possible to use a secret to pull a pod from a private repository within a pod spec ([link](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret)):

```
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: regcred
```

This seems a bit clunky though for a lot of use cases.  The **ContainerRegistry** implementation will handle this transparently and user's who don't want everyone in the cluster to be able to pull from all container registries can use the approach above.
