### ISSUE TITLE
Cluster FeatureGates: Enable ephemeral debug container support in neonKUBE clusters

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1384]
Let's add a cluster-level option to `ClusterDefinition` that enables ephermial debug container support:

https://downey.io/blog/kubernetes-ephemeral-debug-container-tcpdump/

This looks super useful and should be enabled by default.

**Comment by jefflill** [comment]
Here's information about the Kubernetes feature gates:

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

It looks like **EphemeralContainers** has been disabled and alpha since Kubernetes v1.16 and enabled and beta since v1.23.

Perhaps we should define a new `ClusterDefinition.FeatureGates` property as a dictionary of name/bool values where the user can specify overrides for cluster features.

**Comment by jefflill** [comment]
Here's a good post describing how to specify these feature gates.  These used to be specified for heach component (kubelet, kube-api-server, kube-schedule,...) but that's been depreciated and all of the feature gates can be specified on the API server:

https://stackoverflow.com/questions/59814862/how-do-you-enable-feature-gates-in-k8s

For neonKUBE, we'll be able to edit the API server static pod config on the masters at:

```
/etc/kubernetes/manifests/kube-apiserver.yaml
```

**Comment by jefflill** [comment]
The `kube-apiserver.yam` manifest looks like:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 100.64.0.2:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=0.0.0.0
    - --allow-privileged=true
    - --api-audiences=api
    - --authorization-mode=Node,RBAC
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --default-not-ready-toleration-seconds=30
    - --default-unreachable-toleration-seconds=30
    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,Priority,ResourceQuota
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --logging-format=json
    - --oidc-client-id=kubernetes
    - --oidc-groups-claim=groups
    - --oidc-groups-prefix=
    - --oidc-issuer-url=https://sso.f4ef74204ee34bbb888e823b3f0c8e3b.neoncluster.io
    - --oidc-username-claim=email
    - --oidc-username-prefix=-
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-issuer=kubernetes.default.svc
    - --service-account-key-file=/etc/kubernetes/pki/sa.key
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.253.0.0/16
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: neon-registry.node.local/kube-apiserver:v1.21.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 100.64.0.2
        path: /livez
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-apiserver
    ...
```

We'll need edit this by inserting a `- --feature-gates=...` line at the end of the command arguments.
