### ISSUE TITLE
Inconsistent OpenEBS related naming

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1672]
```
     vm:
       osDisk: 256GiB
       openEbsDisk: 128GiB
 
    azure:
      diskSize: 512GiB
      openEBSDiskSize: 512GiB
```

I did not look at AWS
