### ISSUE TITLE
NeonService JSON log lines are being split

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1675]
@marcusbooyah noticed that log lines are being split after the  `NeonService` migration to OpenTelemetry and JSON formatted logs.

We original thought this may have been due to enabling batch log processing but that didn't really make sense and I also confirmed that we're not batching anyway.

It looks like we're writing the log lines correctly.  This may be a **CRI-O** issue.  Docker appears to have a similar issue where it automatically splits long lines and it appears that **promtail** can be configured to handle this: https://github.com/grafana/loki/issues/2281#issuecomment-1105188098

Here's **haircommander** discussing this for CRI-O: https://github.com/cri-o/cri-o/issues/4432

It looks like CRI-O is reading logs using an 8K buffer and if a log line happens to be split across an 8K boundary, CRI-O will split that into two lines using the **P and F annotations**.  So this isn't really a max line length thing, but longer lines will make this more common.

I think this Grafana node agent config will do the track:
  ```
  additionalScrapeConfigs:
  - multiline:
      # Identify a zero-width space as first line of a multiline block and
      # then have the agent remove that as well as the linefeed.  We'll give
      # the agent up to 3 seconds for the remaining part of the log to be
      # captured.
      firstline: '^\x{200B}'
      max_wait_time: 3s
    - replace:
        expression: '^(\x{200B})'
        replace: ''
    - replace:
        expression: '([\n])'
        replace: ''
  ```
