### ISSUE TITLE
user cluster minio buckets reference [us-west-2] region?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1854]
@marcusbooyah: Does this make sense?

$\neonKUBE\Lib\Neon.Kube.Setup\Resources\Helm\mimir\templates\buckets.yaml:
---

```
apiVersion: minio.neonkube.io/v1alpha1
kind: MinioBucket
metadata:
  name: mimir-tsdb
  namespace: neon-system
spec:
  quota:
    hard: true
    limit: {{ .Values.minio.bucket.mimirTsdb.quota }}
  region: us-west-2        <--- do we need this?
  tenant: minio
---
apiVersion: minio.neonkube.io/v1alpha1
kind: MinioBucket
metadata:
  name: mimir-ruler
  namespace: neon-system
spec:
  region: us-west-2        <--- do we need this?
  tenant: minio
```
