### ISSUE TITLE
OpenEBS pods getting evicted

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1897]
It looks like this is because resource requests are not being set so they are getting evicted when low on memory. 

The priority class name is also wrong in this case: `priorityClassName: user-medium`

```
 status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-03-12T11:51:39Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2024-03-12T11:52:43Z'
      reason: ContainersNotReady
      message: >-
        containers with unready status: [cstor-pool-mgmt cstor-pool
        maya-exporter]
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2024-03-12T11:52:43Z'
      reason: ContainersNotReady
      message: >-
        containers with unready status: [cstor-pool-mgmt cstor-pool
        maya-exporter]
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-03-12T11:51:39Z'
  message: >-
    The node was low on resource: memory. Container cstor-pool-mgmt was using
    27484Ki, which exceeds its request of 0. Container maya-exporter was using
    9736Ki, which exceeds its request of 0. Container cstor-pool was using
    51480Ki, which exceeds its request of 0. 
  reason: Evicted
  hostIP: 10.100.42.154
  podIP: 10.254.59.37
  podIPs:
    - ip: 10.254.59.37
  startTime: '2024-03-12T11:51:39Z'
  containerStatuses:
    - name: cstor-pool
      state:
        terminated:
          exitCode: 137
          reason: ContainerStatusUnknown
          message: The container could not be located when the pod was terminated
          startedAt: null
          finishedAt: null
      lastState:
        terminated:
          exitCode: 137
          reason: ContainerStatusUnknown
          message: >-
            The container could not be located when the pod was deleted.  The
            container used to be Running
          startedAt: null
          finishedAt: null
      ready: false
      restartCount: 1
      image: registry.neon.local/neonkube/openebs-cstor-pool:3.2.0
      imageID: ''
      started: false
    - name: cstor-pool-mgmt
      state:
        terminated:
          exitCode: 137
          reason: ContainerStatusUnknown
          message: The container could not be located when the pod was terminated
          startedAt: null
          finishedAt: null
      lastState:
        terminated:
          exitCode: 137
          reason: ContainerStatusUnknown
          message: >-
            The container could not be located when the pod was deleted.  The
            container used to be Running
          startedAt: null
          finishedAt: null
      ready: false
      restartCount: 1
      image: registry.neon.local/neonkube/openebs-cstor-pool-manager:3.2.0
      imageID: ''
      started: false
    - name: maya-exporter
      state:
        terminated:
          exitCode: 137
          reason: ContainerStatusUnknown
          message: The container could not be located when the pod was terminated
          startedAt: null
          finishedAt: null
      lastState:
        terminated:
          exitCode: 137
          reason: ContainerStatusUnknown
          message: >-
            The container could not be located when the pod was deleted.  The
            container used to be Running
          startedAt: null
          finishedAt: null
      ready: false
      restartCount: 1
      image: registry.neon.local/neonkube/openebs-m-exporter:3.2.0
      imageID: ''
      started: false
  qosClass: BestEffort
```
