### ISSUE TITLE
Cluster Setup: Istio setup is hanging for single node clusters

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#542]
Cluster setup fails for single node clusters when installing Istio.  The hang appears to happen just before the Istio install when the script is confirming that the 58 CRDs we're successfully installed.

Perhaps this is related to the master scheduling taint change/fix you may a while back?

Here's the cluster configuration I was using (for my home network):

```
name: home-tiny
datacenter: woodinville
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: hyperv-local
  vmDriveFolder: D:\\VM
network:
  premiseSubnet: 10.0.0.0/16
  nodesSubnet: 10.0.0.0/16
nodeOptions:
  upgrade: none
  passwordLength: 20
nodes:
  master-0:
    role: master
    privateAddress: 10.0.0.30
```
