### ISSUE TITLE
Dashboards should be Custom Resources

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#613]
Create a [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) for neonKUBE dashboards. The plan is to then have the `WinDesktop` query the kube API server for the latest list of dashboards to proxide proxies for.

```yaml
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "dashboard-proxy.neonkube.io"
spec:
  group: "neonkube.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "dashboardProxies"
    singular: "dashboardProxy"
    kind: "DashboardProxy"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["serviceName","ports"]
          properties:
            serviceName:
              type: "string"
              minimum: 1
            ports:
              type: array
                items:
                  type: integer
            minimum: 1
---
apiVersion: neonkube.io/v1alpha1
kind: DashboardProxy
metadata:
  name: grafana-dashboard
  namespace: monitoring
spec:
  serviceName: grafana
  ports:
    - 80
```
