### ISSUE TITLE
Update Ubuntu images to: 18.04.3

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#625]
Ubuntu has a new 18.04.3 point release.  We need to rebuild the VM images:

- [x] Hyper-V
- [x] XenServer/XCP-ng

**Comment by jefflill** [comment]
@marcusbooyah: I've built and uploaded the Hyper-V and XCP node VM templates and have removed the old templates from the WowRack XCP host machines (which means the new templates will be downloaded next time you setup a cluster).

You'll need to run this command on your workstations to remove the cached Hyper-V template:
```
neon cluster prepare --remove-templates
```

It looks like Ubuntu is running fine but I wasn't able to setup a tiny cluster on my home workstation.  The prepare step worked but **setup is hanging**.  Here's the cluster configuration I was using:
```
name: home-tiny
datacenter: woodinville
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: hyperv-local
  vmDriveFolder: D:\\VM
network:
  premiseSubnet: 10.0.0.0/16
  nodesSubnet: 10.0.0.0/16
nodeOptions:
  upgrade: none
  passwordLength: 20
nodes:
  master-0:
    role: master
    privateAddress: 10.0.0.30
```
