### ISSUE TITLE
Single node cluster setup fails

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#814]
Cluster setup of a single node cluster appears to hang while configuring Istio.  Here's the cluster definition I was using (configured for my home network):
```
name: home-tiny
datacenter: woodinville
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: hyperv-local
  vmDriveFolder: D:\\VM
network:
  premiseSubnet: 10.0.0.0/16
  nodesSubnet: 10.0.0.0/16
nodeOptions:
  upgrade: none
  passwordLength: 20
nodes:
  master-0:
    role: master
    privateAddress: 10.0.0.30
```
Here's the setup log file for the node, obtained from **"%USERPROFILE%\\.neonkube\log"**:

&nbsp;&nbsp;&nbsp;&nbsp;[master-0.log](https://github.com/nforgeio/neonKUBE/files/4547463/master-0.log)

Any fix should also be backported to the **release-1.2.3** branch as well.  I'm planning on doing a 1.x based release for Loopie at some point.
